version: '3.7'
volumes:
  db-data:
    driver: local

services:
  database:
    build: docker/postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sasql
      POSTGRES_DB: badger
    ports:
      - 5432:5432
    volumes:
      - 'db-data:/var/lib/pgsql'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
  mailer:
    image: 'schickling/mailcatcher'
    ports: [ 1025, 1080 ]
