version: '3.7'
volumes:
  db-data:
  test-data:

services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'main'
    ports:
      - 3306:3306
    volumes:
      - 'db-data:/var/lib/mysql'
  test:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'main'
    ports:
      - 3307:3306
    volumes:
      - 'test-data:/var/lib/mysql'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
      - test
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: symfony
    ports:
      - 81:80
    volumes:
      - .:/app/
    depends_on:
      - database
  mailer:
    image: 'schickling/mailcatcher'
    ports: [ 1025, 1080 ]
